version: '3'

services:
  client-gateway:
    image: obssesion/client-gateway-ms:1.0
    ports:
      - "${CLIENT_GATEWAY_PORT}:3010"
    environment:
      - PORT=3010
      - NATS_SERVERS=nats://nats-server:4222

  electrica-ms:
    image: obssesion/electrica-ms:1.0
    depends_on:
      - vym-db
    environment:
      - PORT=3007
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://postgres:123456@vym-db:5432/vymdb?schema=public

  auth-ms:
    image: obssesion/auth-ms:1.0
    environment:
      - PORT=3013
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./auth-vym-ms/data:/usr/src/app/data
    ports:
      - "3013:3013"
    restart: unless-stopped

  vym-db:
    image: postgres:16.2
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=vymdb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      
  nats-server:
    image: nats:2.1
    ports:
      - "4222:4222"
      - "8222:8222"
